"""removed state from user in chat

Revision ID: 4e13a4f25b81
Revises: 8562b0196eb0
Create Date: 2025-04-15 13:00:57.771575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e13a4f25b81'
down_revision: Union[str, None] = '8562b0196eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chat', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chat', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
