"""session_fixed

Revision ID: a7afc6b38cdc
Revises: 428c390c53cc
Create Date: 2025-04-19 19:28:13.854832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7afc6b38cdc'
down_revision: Union[str, None] = '428c390c53cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('one_active_session_per_game', 'trading_session', ['game_id'], unique=True, postgresql_where=sa.text('is_finished IS FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_active_session_per_game', table_name='trading_session', postgresql_where=sa.text('is_finished IS FALSE'))
    # ### end Alembic commands ###
