"""session_limit added

Revision ID: 234962f39a44
Revises: de64069b6467
Create Date: 2025-04-13 22:05:20.901905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234962f39a44'
down_revision: Union[str, None] = 'de64069b6467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('session_limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'session_limit')
    # ### end Alembic commands ###
