"""state to chat added

Revision ID: 18db31bce744
Revises: 2849a453d177
Create Date: 2025-04-14 13:07:43.870560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18db31bce744'
down_revision: Union[str, None] = '2849a453d177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chat', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_chat', 'state')
    # ### end Alembic commands ###
