"""winner_id fixed

Revision ID: 2849a453d177
Revises: ca0b124d88e3
Create Date: 2025-04-13 22:29:44.081201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2849a453d177'
down_revision: Union[str, None] = 'ca0b124d88e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_winner_id_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'user_game', ['winner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_winner_id_fkey', 'game', 'telegram_user', ['winner_id'], ['id'])
    # ### end Alembic commands ###
