"""placed cur balance to user in game

Revision ID: d8978c835da7
Revises: 4e13a4f25b81
Create Date: 2025-04-15 13:02:23.071071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8978c835da7'
down_revision: Union[str, None] = '4e13a4f25b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chat', 'cur_balance')
    op.add_column('user_game', sa.Column('cur_balance', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game', 'cur_balance')
    op.add_column('user_chat', sa.Column('cur_balance', sa.NUMERIC(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
