"""updated

Revision ID: 8562b0196eb0
Revises: 84c97c650bd4
Create Date: 2025-04-14 13:57:33.603286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8562b0196eb0'
down_revision: Union[str, None] = '84c97c650bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_winner_id_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'telegram_user', ['winner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_winner_id_fkey', 'game', 'user_game', ['winner_id'], ['id'])
    # ### end Alembic commands ###
