"""player fields fixed

Revision ID: ca0b124d88e3
Revises: 234962f39a44
Create Date: 2025-04-13 22:10:13.433684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0b124d88e3'
down_revision: Union[str, None] = '234962f39a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_chat', 'state')
    op.add_column('user_chat', sa.Column('state', sa.String(), nullable=False))
    op.add_column('user_chat', sa.Column('cur_balance', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chat', 'cur_balance')
    op.drop_column('user_chat', 'state')
    op.add_column('telegram_chat', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
